menus:
  settings:
    title: "<dark_gray>Server Settings"
    size: 27
    items:
      pvp:
        slot: 11
        true-state:
          material: LIME_WOOL
          name: "<yellow><bold>PvP Toggle"
          lore:
            - "<gray>Current: <green>Enabled"
            - ""
            - "<yellow>Click to disable!"
        false-state:
          material: RED_WOOL
          name: "<yellow><bold>PvP Toggle"
          lore:
            - "<gray>Current: <red>Disabled"
            - ""
            - "<yellow>Click to enable!"
      time:
        slot: 13
        true-state:
          material: SUNFLOWER
          name: "<aqua><bold>Time Toggle"
          lore:
            - "<gray>Current: <yellow>Day"
            - ""
            - "<yellow>Click to set Night!"
        false-state:
          material: CLOCK
          name: "<aqua><bold>Time Toggle"
          lore:
            - "<gray>Current: <blue>Night"
            - ""
            - "<yellow>Click to set Day!"
      weather:
        slot: 15
        true-state:
          material: WATER_BUCKET
          name: "<light_purple><bold>Weather Toggle"
          lore:
            - "<gray>Current: <blue>Raining"
            - ""
            - "<yellow>Click to clear weather!"
        false-state:
          material: LAVA_BUCKET
          name: "<light_purple><bold>Weather Toggle"
          lore:
            - "<gray>Current: <gold>Clear"
            - ""
            - "<yellow>Click to make it rain!"
